=== michaelflppv/mixup/gedlib/data/collections/GraphCollection.dtd
<!-- 

GraphCollection
Document Type Definition  

This file is part of GEDLIB (1.0)

-->

<!ELEMENT GraphCollection (graph+)>
<!ELEMENT graph EMPTY>
<!ATTLIST graph file ID #REQUIRED>
<!ATTLIST graph class CDATA #REQUIRED>

=== michaelflppv/mixup/gedlib/median/collections/AIDS-EDIT-NON-ISO-30-1.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="molid663607_subnode_13_to_W.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Tl.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Se.gxl" class="1"/>
	<graph file="molid663607_subedge_1_2_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Sn.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Se.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_K.gxl" class="1"/>
	<graph file="molid663607_addedge_5_14_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Pd.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Zn.gxl" class="1"/>
	<graph file="molid663607_addnode_B.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Se.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Ru.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Ru.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_S.gxl" class="1"/>
	<graph file="molid663607_addedge_5_6_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Au.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Mg.gxl" class="1"/>
	<graph file="molid663607_addedge_0_9_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_7_14_label_2.gxl" class="1"/>
	<graph file="molid663607_addnode_Pd.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Hg.gxl" class="1"/>
	<graph file="molid663607_addnode_Au.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Hg.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_B.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Ho.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Cu.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Pt.gxl" class="1"/>
	<graph file="molid663607_addedge_1_14_label_1.gxl" class="1"/>
	<graph file="molid663607_subedge_2_7_to_1.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Mg.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Ga.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_F.gxl" class="1"/>
	<graph file="molid663607_addnode_N.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Ga.gxl" class="1"/>
	<graph file="molid663607_addedge_3_9_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Pb.gxl" class="1"/>
	<graph file="molid663607_addedge_1_31_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_6_31_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_13_15_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_N.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_W.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Cu.gxl" class="1"/>
	<graph file="molid663607_addnode_Rh.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Sn.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Si.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Br.gxl" class="1"/>
	<graph file="molid663607_subedge_30_31_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Sb.gxl" class="1"/>
	<graph file="molid663607_addedge_1_3_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_K.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Sb.gxl" class="1"/>
	<graph file="molid663607_addedge_9_15_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_C.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Te.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_P.gxl" class="1"/>
	<graph file="molid663607_addnode_Li.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_B.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Bi.gxl" class="1"/>
	<graph file="molid663607_subedge_12_14_to_2.gxl" class="1"/>
	<graph file="molid663607_deledge_30_31.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Rh.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Hg.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_I.gxl" class="1"/>
	<graph file="molid663607_addedge_5_14_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Ho.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_S.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Ni.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Br.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Pd.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Zn.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Hg.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Br.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Ga.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Ni.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_W.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Pd.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Se.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Ho.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Bi.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Cu.gxl" class="1"/>
	<graph file="molid663607_addedge_9_11_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Br.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_F.gxl" class="1"/>
	<graph file="molid663607_addedge_7_13_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_5_10_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_10_14_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Hg.gxl" class="1"/>
	<graph file="molid663607_subedge_17_19_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Cu.gxl" class="1"/>
	<graph file="molid663607_addedge_0_9_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Pb.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_F.gxl" class="1"/>
	<graph file="molid663607_addedge_0_6_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_6_14_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_O.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Au.gxl" class="1"/>
	<graph file="molid663607_addedge_10_14_label_1.gxl" class="1"/>
	<graph file="molid663607_addedge_5_10_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Tb.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Pd.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Co.gxl" class="1"/>
	<graph file="molid663607_deledge_5_9.gxl" class="1"/>
	<graph file="molid663607_deledge_17_19.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Mg.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Pb.gxl" class="1"/>
	<graph file="molid663607_subedge_0_1_to_1.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_B.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Zn.gxl" class="1"/>
	<graph file="molid663607_addedge_3_14_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Te.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_B.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Ru.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Zn.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Br.gxl" class="1"/>
	<graph file="molid663607_subedge_15_16_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Ru.gxl" class="1"/>
	<graph file="molid663607_addedge_0_6_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Ho.gxl" class="1"/>
	<graph file="molid663607_addnode_As.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Na.gxl" class="1"/>
	<graph file="molid663607_subedge_5_9_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_As.gxl" class="1"/>
	<graph file="molid663607_addedge_6_13_label_1.gxl" class="1"/>
	<graph file="molid663607_addedge_7_8_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Co.gxl" class="1"/>
	<graph file="molid663607_addedge_1_9_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Ho.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Pt.gxl" class="1"/>
	<graph file="molid663607_addnode_Ho.gxl" class="1"/>
	<graph file="molid663607_addedge_7_9_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_O.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Mg.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_B.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Ge.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_B.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_K.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Na.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Li.gxl" class="1"/>
	<graph file="molid663607_addedge_9_15_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Li.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Au.gxl" class="1"/>
	<graph file="molid663607_subedge_4_5_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Na.gxl" class="1"/>
	<graph file="molid663607_addedge_3_6_label_1.gxl" class="1"/>
	<graph file="molid663607_deledge_16_17.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Ni.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Pd.gxl" class="1"/>
	<graph file="molid663607_addnode_Cu.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_As.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Na.gxl" class="1"/>
	<graph file="molid663607_addedge_0_13_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_3_10_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Mg.gxl" class="1"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/tests/unit_tests/collections/Mutagenicity_train.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="molecule_2876.gxl" class="mutagen"/>
	<graph file="molecule_2746.gxl" class="mutagen"/>
	<graph file="molecule_1302.gxl" class="mutagen"/>
	<graph file="molecule_1179.gxl" class="mutagen"/>
	<graph file="molecule_4024.gxl" class="mutagen"/>
	<graph file="molecule_1394.gxl" class="mutagen"/>
	<graph file="molecule_1683.gxl" class="mutagen"/>
	<graph file="molecule_3682.gxl" class="mutagen"/>
	<graph file="molecule_830.gxl" class="mutagen"/>
	<graph file="molecule_1203.gxl" class="mutagen"/>
	<graph file="molecule_493.gxl" class="mutagen"/>
	<graph file="molecule_589.gxl" class="mutagen"/>
	<graph file="molecule_428.gxl" class="mutagen"/>
	<graph file="molecule_890.gxl" class="mutagen"/>
	<graph file="molecule_1381.gxl" class="mutagen"/>
	<graph file="molecule_615.gxl" class="mutagen"/>
	<graph file="molecule_3170.gxl" class="mutagen"/>
	<graph file="molecule_1342.gxl" class="mutagen"/>
	<graph file="molecule_3760.gxl" class="mutagen"/>
	<graph file="molecule_957.gxl" class="mutagen"/>
	<graph file="molecule_2561.gxl" class="mutagen"/>
	<graph file="molecule_2606.gxl" class="mutagen"/>
	<graph file="molecule_968.gxl" class="mutagen"/>
	<graph file="molecule_1952.gxl" class="mutagen"/>
	<graph file="molecule_1764.gxl" class="mutagen"/>
	<graph file="molecule_1086.gxl" class="nonmutagen"/>
	<graph file="molecule_461.gxl" class="nonmutagen"/>
	<graph file="molecule_2297.gxl" class="nonmutagen"/>
	<graph file="molecule_2224.gxl" class="nonmutagen"/>
	<graph file="molecule_4063.gxl" class="nonmutagen"/>
	<graph file="molecule_2169.gxl" class="nonmutagen"/>
	<graph file="molecule_3301.gxl" class="nonmutagen"/>
	<graph file="molecule_1464.gxl" class="nonmutagen"/>
	<graph file="molecule_2424.gxl" class="nonmutagen"/>
	<graph file="molecule_3483.gxl" class="nonmutagen"/>
	<graph file="molecule_4119.gxl" class="nonmutagen"/>
	<graph file="molecule_62.gxl" class="nonmutagen"/>
	<graph file="molecule_1507.gxl" class="nonmutagen"/>
	<graph file="molecule_803.gxl" class="nonmutagen"/>
	<graph file="molecule_4110.gxl" class="nonmutagen"/>
	<graph file="molecule_2651.gxl" class="nonmutagen"/>
	<graph file="molecule_1180.gxl" class="nonmutagen"/>
	<graph file="molecule_2575.gxl" class="nonmutagen"/>
	<graph file="molecule_1130.gxl" class="nonmutagen"/>
	<graph file="molecule_3816.gxl" class="nonmutagen"/>
	<graph file="molecule_3957.gxl" class="nonmutagen"/>
	<graph file="molecule_3501.gxl" class="nonmutagen"/>
	<graph file="molecule_132.gxl" class="nonmutagen"/>
	<graph file="molecule_3961.gxl" class="nonmutagen"/>
	<graph file="molecule_2782.gxl" class="nonmutagen"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/median/collections/Letter_N.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="NP1_0050.gxl" class="N"/>
	<graph file="NP1_0051.gxl" class="N"/>
	<graph file="NP1_0052.gxl" class="N"/>
	<graph file="NP1_0053.gxl" class="N"/>
	<graph file="NP1_0054.gxl" class="N"/>
	<graph file="NP1_0055.gxl" class="N"/>
	<graph file="NP1_0056.gxl" class="N"/>
	<graph file="NP1_0057.gxl" class="N"/>
	<graph file="NP1_0058.gxl" class="N"/>
	<graph file="NP1_0059.gxl" class="N"/>
	<graph file="NP1_0060.gxl" class="N"/>
	<graph file="NP1_0061.gxl" class="N"/>
	<graph file="NP1_0062.gxl" class="N"/>
	<graph file="NP1_0063.gxl" class="N"/>
	<graph file="NP1_0064.gxl" class="N"/>
	<graph file="NP1_0065.gxl" class="N"/>
	<graph file="NP1_0066.gxl" class="N"/>
	<graph file="NP1_0067.gxl" class="N"/>
	<graph file="NP1_0068.gxl" class="N"/>
	<graph file="NP1_0069.gxl" class="N"/>
	<graph file="NP1_0070.gxl" class="N"/>
	<graph file="NP1_0071.gxl" class="N"/>
	<graph file="NP1_0072.gxl" class="N"/>
	<graph file="NP1_0073.gxl" class="N"/>
	<graph file="NP1_0074.gxl" class="N"/>
	<graph file="NP1_0075.gxl" class="N"/>
	<graph file="NP1_0076.gxl" class="N"/>
	<graph file="NP1_0077.gxl" class="N"/>
	<graph file="NP1_0078.gxl" class="N"/>
	<graph file="NP1_0079.gxl" class="N"/>
	<graph file="NP1_0080.gxl" class="N"/>
	<graph file="NP1_0081.gxl" class="N"/>
	<graph file="NP1_0082.gxl" class="N"/>
	<graph file="NP1_0083.gxl" class="N"/>
	<graph file="NP1_0084.gxl" class="N"/>
	<graph file="NP1_0085.gxl" class="N"/>
	<graph file="NP1_0086.gxl" class="N"/>
	<graph file="NP1_0087.gxl" class="N"/>
	<graph file="NP1_0088.gxl" class="N"/>
	<graph file="NP1_0089.gxl" class="N"/>
	<graph file="NP1_0090.gxl" class="N"/>
	<graph file="NP1_0091.gxl" class="N"/>
	<graph file="NP1_0092.gxl" class="N"/>
	<graph file="NP1_0093.gxl" class="N"/>
	<graph file="NP1_0094.gxl" class="N"/>
	<graph file="NP1_0095.gxl" class="N"/>
	<graph file="NP1_0096.gxl" class="N"/>
	<graph file="NP1_0097.gxl" class="N"/>
	<graph file="NP1_0098.gxl" class="N"/>
	<graph file="NP1_0099.gxl" class="N"/>
	<graph file="NP1_0000.gxl" class="N"/>
	<graph file="NP1_0001.gxl" class="N"/>
	<graph file="NP1_0002.gxl" class="N"/>
	<graph file="NP1_0003.gxl" class="N"/>
	<graph file="NP1_0004.gxl" class="N"/>
	<graph file="NP1_0005.gxl" class="N"/>
	<graph file="NP1_0006.gxl" class="N"/>
	<graph file="NP1_0007.gxl" class="N"/>
	<graph file="NP1_0008.gxl" class="N"/>
	<graph file="NP1_0009.gxl" class="N"/>
	<graph file="NP1_0010.gxl" class="N"/>
	<graph file="NP1_0011.gxl" class="N"/>
	<graph file="NP1_0012.gxl" class="N"/>
	<graph file="NP1_0013.gxl" class="N"/>
	<graph file="NP1_0014.gxl" class="N"/>
	<graph file="NP1_0015.gxl" class="N"/>
	<graph file="NP1_0016.gxl" class="N"/>
	<graph file="NP1_0017.gxl" class="N"/>
	<graph file="NP1_0018.gxl" class="N"/>
	<graph file="NP1_0019.gxl" class="N"/>
	<graph file="NP1_0020.gxl" class="N"/>
	<graph file="NP1_0021.gxl" class="N"/>
	<graph file="NP1_0022.gxl" class="N"/>
	<graph file="NP1_0023.gxl" class="N"/>
	<graph file="NP1_0024.gxl" class="N"/>
	<graph file="NP1_0025.gxl" class="N"/>
	<graph file="NP1_0026.gxl" class="N"/>
	<graph file="NP1_0027.gxl" class="N"/>
	<graph file="NP1_0028.gxl" class="N"/>
	<graph file="NP1_0029.gxl" class="N"/>
	<graph file="NP1_0030.gxl" class="N"/>
	<graph file="NP1_0031.gxl" class="N"/>
	<graph file="NP1_0032.gxl" class="N"/>
	<graph file="NP1_0033.gxl" class="N"/>
	<graph file="NP1_0034.gxl" class="N"/>
	<graph file="NP1_0035.gxl" class="N"/>
	<graph file="NP1_0036.gxl" class="N"/>
	<graph file="NP1_0037.gxl" class="N"/>
	<graph file="NP1_0038.gxl" class="N"/>
	<graph file="NP1_0039.gxl" class="N"/>
	<graph file="NP1_0040.gxl" class="N"/>
	<graph file="NP1_0041.gxl" class="N"/>
	<graph file="NP1_0042.gxl" class="N"/>
	<graph file="NP1_0043.gxl" class="N"/>
	<graph file="NP1_0044.gxl" class="N"/>
	<graph file="NP1_0045.gxl" class="N"/>
	<graph file="NP1_0046.gxl" class="N"/>
	<graph file="NP1_0047.gxl" class="N"/>
	<graph file="NP1_0048.gxl" class="N"/>
	<graph file="NP1_0049.gxl" class="N"/>
	<graph file="NP1_0100.gxl" class="N"/>
	<graph file="NP1_0101.gxl" class="N"/>
	<graph file="NP1_0102.gxl" class="N"/>
	<graph file="NP1_0103.gxl" class="N"/>
	<graph file="NP1_0104.gxl" class="N"/>
	<graph file="NP1_0105.gxl" class="N"/>
	<graph file="NP1_0106.gxl" class="N"/>
	<graph file="NP1_0107.gxl" class="N"/>
	<graph file="NP1_0108.gxl" class="N"/>
	<graph file="NP1_0109.gxl" class="N"/>
	<graph file="NP1_0110.gxl" class="N"/>
	<graph file="NP1_0111.gxl" class="N"/>
	<graph file="NP1_0112.gxl" class="N"/>
	<graph file="NP1_0113.gxl" class="N"/>
	<graph file="NP1_0114.gxl" class="N"/>
	<graph file="NP1_0115.gxl" class="N"/>
	<graph file="NP1_0116.gxl" class="N"/>
	<graph file="NP1_0117.gxl" class="N"/>
	<graph file="NP1_0118.gxl" class="N"/>
	<graph file="NP1_0119.gxl" class="N"/>
	<graph file="NP1_0120.gxl" class="N"/>
	<graph file="NP1_0121.gxl" class="N"/>
	<graph file="NP1_0122.gxl" class="N"/>
	<graph file="NP1_0123.gxl" class="N"/>
	<graph file="NP1_0124.gxl" class="N"/>
	<graph file="NP1_0125.gxl" class="N"/>
	<graph file="NP1_0126.gxl" class="N"/>
	<graph file="NP1_0127.gxl" class="N"/>
	<graph file="NP1_0128.gxl" class="N"/>
	<graph file="NP1_0129.gxl" class="N"/>
	<graph file="NP1_0130.gxl" class="N"/>
	<graph file="NP1_0131.gxl" class="N"/>
	<graph file="NP1_0132.gxl" class="N"/>
	<graph file="NP1_0133.gxl" class="N"/>
	<graph file="NP1_0134.gxl" class="N"/>
	<graph file="NP1_0135.gxl" class="N"/>
	<graph file="NP1_0136.gxl" class="N"/>
	<graph file="NP1_0137.gxl" class="N"/>
	<graph file="NP1_0138.gxl" class="N"/>
	<graph file="NP1_0139.gxl" class="N"/>
	<graph file="NP1_0140.gxl" class="N"/>
	<graph file="NP1_0141.gxl" class="N"/>
	<graph file="NP1_0142.gxl" class="N"/>
	<graph file="NP1_0143.gxl" class="N"/>
	<graph file="NP1_0144.gxl" class="N"/>
	<graph file="NP1_0145.gxl" class="N"/>
	<graph file="NP1_0146.gxl" class="N"/>
	<graph file="NP1_0147.gxl" class="N"/>
	<graph file="NP1_0148.gxl" class="N"/>
	<graph file="NP1_0149.gxl" class="N"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/median/collections/Letter_W.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="WP1_0050.gxl" class="W"/>
	<graph file="WP1_0051.gxl" class="W"/>
	<graph file="WP1_0052.gxl" class="W"/>
	<graph file="WP1_0053.gxl" class="W"/>
	<graph file="WP1_0054.gxl" class="W"/>
	<graph file="WP1_0055.gxl" class="W"/>
	<graph file="WP1_0056.gxl" class="W"/>
	<graph file="WP1_0057.gxl" class="W"/>
	<graph file="WP1_0058.gxl" class="W"/>
	<graph file="WP1_0059.gxl" class="W"/>
	<graph file="WP1_0060.gxl" class="W"/>
	<graph file="WP1_0061.gxl" class="W"/>
	<graph file="WP1_0062.gxl" class="W"/>
	<graph file="WP1_0063.gxl" class="W"/>
	<graph file="WP1_0064.gxl" class="W"/>
	<graph file="WP1_0065.gxl" class="W"/>
	<graph file="WP1_0066.gxl" class="W"/>
	<graph file="WP1_0067.gxl" class="W"/>
	<graph file="WP1_0068.gxl" class="W"/>
	<graph file="WP1_0069.gxl" class="W"/>
	<graph file="WP1_0070.gxl" class="W"/>
	<graph file="WP1_0071.gxl" class="W"/>
	<graph file="WP1_0072.gxl" class="W"/>
	<graph file="WP1_0073.gxl" class="W"/>
	<graph file="WP1_0074.gxl" class="W"/>
	<graph file="WP1_0075.gxl" class="W"/>
	<graph file="WP1_0076.gxl" class="W"/>
	<graph file="WP1_0077.gxl" class="W"/>
	<graph file="WP1_0078.gxl" class="W"/>
	<graph file="WP1_0079.gxl" class="W"/>
	<graph file="WP1_0080.gxl" class="W"/>
	<graph file="WP1_0081.gxl" class="W"/>
	<graph file="WP1_0082.gxl" class="W"/>
	<graph file="WP1_0083.gxl" class="W"/>
	<graph file="WP1_0084.gxl" class="W"/>
	<graph file="WP1_0085.gxl" class="W"/>
	<graph file="WP1_0086.gxl" class="W"/>
	<graph file="WP1_0087.gxl" class="W"/>
	<graph file="WP1_0088.gxl" class="W"/>
	<graph file="WP1_0089.gxl" class="W"/>
	<graph file="WP1_0090.gxl" class="W"/>
	<graph file="WP1_0091.gxl" class="W"/>
	<graph file="WP1_0092.gxl" class="W"/>
	<graph file="WP1_0093.gxl" class="W"/>
	<graph file="WP1_0094.gxl" class="W"/>
	<graph file="WP1_0095.gxl" class="W"/>
	<graph file="WP1_0096.gxl" class="W"/>
	<graph file="WP1_0097.gxl" class="W"/>
	<graph file="WP1_0098.gxl" class="W"/>
	<graph file="WP1_0099.gxl" class="W"/>
	<graph file="WP1_0000.gxl" class="W"/>
	<graph file="WP1_0001.gxl" class="W"/>
	<graph file="WP1_0002.gxl" class="W"/>
	<graph file="WP1_0003.gxl" class="W"/>
	<graph file="WP1_0004.gxl" class="W"/>
	<graph file="WP1_0005.gxl" class="W"/>
	<graph file="WP1_0006.gxl" class="W"/>
	<graph file="WP1_0007.gxl" class="W"/>
	<graph file="WP1_0008.gxl" class="W"/>
	<graph file="WP1_0009.gxl" class="W"/>
	<graph file="WP1_0010.gxl" class="W"/>
	<graph file="WP1_0011.gxl" class="W"/>
	<graph file="WP1_0012.gxl" class="W"/>
	<graph file="WP1_0013.gxl" class="W"/>
	<graph file="WP1_0014.gxl" class="W"/>
	<graph file="WP1_0015.gxl" class="W"/>
	<graph file="WP1_0016.gxl" class="W"/>
	<graph file="WP1_0017.gxl" class="W"/>
	<graph file="WP1_0018.gxl" class="W"/>
	<graph file="WP1_0019.gxl" class="W"/>
	<graph file="WP1_0020.gxl" class="W"/>
	<graph file="WP1_0021.gxl" class="W"/>
	<graph file="WP1_0022.gxl" class="W"/>
	<graph file="WP1_0023.gxl" class="W"/>
	<graph file="WP1_0024.gxl" class="W"/>
	<graph file="WP1_0025.gxl" class="W"/>
	<graph file="WP1_0026.gxl" class="W"/>
	<graph file="WP1_0027.gxl" class="W"/>
	<graph file="WP1_0028.gxl" class="W"/>
	<graph file="WP1_0029.gxl" class="W"/>
	<graph file="WP1_0030.gxl" class="W"/>
	<graph file="WP1_0031.gxl" class="W"/>
	<graph file="WP1_0032.gxl" class="W"/>
	<graph file="WP1_0033.gxl" class="W"/>
	<graph file="WP1_0034.gxl" class="W"/>
	<graph file="WP1_0035.gxl" class="W"/>
	<graph file="WP1_0036.gxl" class="W"/>
	<graph file="WP1_0037.gxl" class="W"/>
	<graph file="WP1_0038.gxl" class="W"/>
	<graph file="WP1_0039.gxl" class="W"/>
	<graph file="WP1_0040.gxl" class="W"/>
	<graph file="WP1_0041.gxl" class="W"/>
	<graph file="WP1_0042.gxl" class="W"/>
	<graph file="WP1_0043.gxl" class="W"/>
	<graph file="WP1_0044.gxl" class="W"/>
	<graph file="WP1_0045.gxl" class="W"/>
	<graph file="WP1_0046.gxl" class="W"/>
	<graph file="WP1_0047.gxl" class="W"/>
	<graph file="WP1_0048.gxl" class="W"/>
	<graph file="WP1_0049.gxl" class="W"/>
	<graph file="WP1_0100.gxl" class="W"/>
	<graph file="WP1_0101.gxl" class="W"/>
	<graph file="WP1_0102.gxl" class="W"/>
	<graph file="WP1_0103.gxl" class="W"/>
	<graph file="WP1_0104.gxl" class="W"/>
	<graph file="WP1_0105.gxl" class="W"/>
	<graph file="WP1_0106.gxl" class="W"/>
	<graph file="WP1_0107.gxl" class="W"/>
	<graph file="WP1_0108.gxl" class="W"/>
	<graph file="WP1_0109.gxl" class="W"/>
	<graph file="WP1_0110.gxl" class="W"/>
	<graph file="WP1_0111.gxl" class="W"/>
	<graph file="WP1_0112.gxl" class="W"/>
	<graph file="WP1_0113.gxl" class="W"/>
	<graph file="WP1_0114.gxl" class="W"/>
	<graph file="WP1_0115.gxl" class="W"/>
	<graph file="WP1_0116.gxl" class="W"/>
	<graph file="WP1_0117.gxl" class="W"/>
	<graph file="WP1_0118.gxl" class="W"/>
	<graph file="WP1_0119.gxl" class="W"/>
	<graph file="WP1_0120.gxl" class="W"/>
	<graph file="WP1_0121.gxl" class="W"/>
	<graph file="WP1_0122.gxl" class="W"/>
	<graph file="WP1_0123.gxl" class="W"/>
	<graph file="WP1_0124.gxl" class="W"/>
	<graph file="WP1_0125.gxl" class="W"/>
	<graph file="WP1_0126.gxl" class="W"/>
	<graph file="WP1_0127.gxl" class="W"/>
	<graph file="WP1_0128.gxl" class="W"/>
	<graph file="WP1_0129.gxl" class="W"/>
	<graph file="WP1_0130.gxl" class="W"/>
	<graph file="WP1_0131.gxl" class="W"/>
	<graph file="WP1_0132.gxl" class="W"/>
	<graph file="WP1_0133.gxl" class="W"/>
	<graph file="WP1_0134.gxl" class="W"/>
	<graph file="WP1_0135.gxl" class="W"/>
	<graph file="WP1_0136.gxl" class="W"/>
	<graph file="WP1_0137.gxl" class="W"/>
	<graph file="WP1_0138.gxl" class="W"/>
	<graph file="WP1_0139.gxl" class="W"/>
	<graph file="WP1_0140.gxl" class="W"/>
	<graph file="WP1_0141.gxl" class="W"/>
	<graph file="WP1_0142.gxl" class="W"/>
	<graph file="WP1_0143.gxl" class="W"/>
	<graph file="WP1_0144.gxl" class="W"/>
	<graph file="WP1_0145.gxl" class="W"/>
	<graph file="WP1_0146.gxl" class="W"/>
	<graph file="WP1_0147.gxl" class="W"/>
	<graph file="WP1_0148.gxl" class="W"/>
	<graph file="WP1_0149.gxl" class="W"/>
</GraphCollection>
