=== michaelflppv/mixup/gedlib/data/collections/GraphCollection.dtd
<!-- 

GraphCollection
Document Type Definition  

This file is part of GEDLIB (1.0)

-->

<!ELEMENT GraphCollection (graph+)>
<!ELEMENT graph EMPTY>
<!ATTLIST graph file ID #REQUIRED>
<!ATTLIST graph class CDATA #REQUIRED>

=== michaelflppv/mixup/gedlib/data/collections/mao.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="molecule00.gxl" class="0"/>
	<graph file="molecule01.gxl" class="0"/>
	<graph file="molecule02.gxl" class="0"/>
	<graph file="molecule03.gxl" class="0"/>
	<graph file="molecule04.gxl" class="1"/>
	<graph file="molecule05.gxl" class="0"/>
	<graph file="molecule06.gxl" class="0"/>
	<graph file="molecule07.gxl" class="1"/>
	<graph file="molecule08.gxl" class="0"/>
	<graph file="molecule09.gxl" class="0"/>
	<graph file="molecule10.gxl" class="1"/>
	<graph file="molecule11.gxl" class="0"/>
	<graph file="molecule12.gxl" class="0"/>
	<graph file="molecule13.gxl" class="0"/>
	<graph file="molecule14.gxl" class="1"/>
	<graph file="molecule15.gxl" class="0"/>
	<graph file="molecule16.gxl" class="1"/>
	<graph file="molecule17.gxl" class="1"/>
	<graph file="molecule18.gxl" class="1"/>
	<graph file="molecule19.gxl" class="1"/>
	<graph file="molecule20.gxl" class="1"/>
	<graph file="molecule21.gxl" class="1"/>
	<graph file="molecule22.gxl" class="1"/>
	<graph file="molecule23.gxl" class="1"/>
	<graph file="molecule24.gxl" class="0"/>
	<graph file="molecule25.gxl" class="1"/>
	<graph file="molecule26.gxl" class="1"/>
	<graph file="molecule27.gxl" class="1"/>
	<graph file="molecule28.gxl" class="0"/>
	<graph file="molecule29.gxl" class="0"/>
	<graph file="molecule30.gxl" class="0"/>
	<graph file="molecule31.gxl" class="0"/>
	<graph file="molecule32.gxl" class="1"/>
	<graph file="molecule33.gxl" class="1"/>
	<graph file="molecule34.gxl" class="1"/>
	<graph file="molecule35.gxl" class="0"/>
	<graph file="molecule36.gxl" class="1"/>
	<graph file="molecule37.gxl" class="1"/>
	<graph file="molecule38.gxl" class="1"/>
	<graph file="molecule39.gxl" class="0"/>
	<graph file="molecule40.gxl" class="0"/>
	<graph file="molecule41.gxl" class="0"/>
	<graph file="molecule42.gxl" class="0"/>
	<graph file="molecule43.gxl" class="0"/>
	<graph file="molecule44.gxl" class="1"/>
	<graph file="molecule45.gxl" class="1"/>
	<graph file="molecule46.gxl" class="1"/>
	<graph file="molecule47.gxl" class="0"/>
	<graph file="molecule48.gxl" class="0"/>
	<graph file="molecule49.gxl" class="0"/>
	<graph file="molecule50.gxl" class="0"/>
	<graph file="molecule51.gxl" class="0"/>
	<graph file="molecule52.gxl" class="0"/>
	<graph file="molecule53.gxl" class="1"/>
	<graph file="molecule54.gxl" class="0"/>
	<graph file="molecule55.gxl" class="0"/>
	<graph file="molecule56.gxl" class="0"/>
	<graph file="molecule57.gxl" class="0"/>
	<graph file="molecule58.gxl" class="1"/>
	<graph file="molecule59.gxl" class="1"/>
	<graph file="molecule60.gxl" class="1"/>
	<graph file="molecule61.gxl" class="0"/>
	<graph file="molecule62.gxl" class="0"/>
	<graph file="molecule63.gxl" class="0"/>
	<graph file="molecule64.gxl" class="0"/>
	<graph file="molecule65.gxl" class="1"/>
	<graph file="molecule66.gxl" class="1"/>
	<graph file="molecule67.gxl" class="0"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/tests/ijprai2020/collections/pah_50.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="11-methylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="benzo[c]chrysene.gxl" class="1"/>
	<graph file="3,12-dimethylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="9,10-dimethylanthracene.gxl" class="1"/>
	<graph file="2,3-dimethylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="dibenzo[c,i]pyrene.gxl" class="1"/>
	<graph file="11-methylbenz[a]anthracene.gxl" class="1"/>
	<graph file="dibenz[a,h]anthracene.gxl" class="1"/>
	<graph file="dibenzo[a,e]pyrene.gxl" class="1"/>
	<graph file="benzo[e]pyrene.gxl" class="1"/>
	<graph file="7,12-dimethylbenz[a]anthracene.gxl" class="1"/>
	<graph file="1,2-dimethylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="6,12-dimethylbenz[a]anthracene.gxl" class="1"/>
	<graph file="dibenz[a,j]anthracene.gxl" class="1"/>
	<graph file="2-methylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="benzo[c]phenanthrene.gxl" class="1"/>
	<graph file="8-methylbenz[a]anthracene.gxl" class="1"/>
	<graph file="6,8-dimethylbenz[a]anthracene.gxl" class="1"/>
	<graph file="12-methylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="10-methylbenz[a]anthracene.gxl" class="1"/>
	<graph file="1-methylbenzo[c]phenanthrene.gxl" class="1"/>
	<graph file="dibenzo[a,l]pyrene.gxl" class="1"/>
	<graph file="tribenzo[a,e,i]pyrene.gxl" class="1"/>
	<graph file="1,3-dimethylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="1,4-dimethylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="dibenz[a,c]anthracene.gxl" class="1"/>
	<graph file="3,6-dimethylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="4,5-dimethylbenzo[a]pyrene.gxl" class="1"/>
	<graph file="benzo[g,h,i]perylene.gxl" class="1"/>
	<graph file="6-methylbenzo[c]phenanthrene.gxl" class="1"/>
	<graph file="naphtho(2,3-a)pyrene.gxl" class="1"/>
	<graph file="7,10-dimethylbenzo[a]pyrene.gxl" class="-1"/>
	<graph file="coronene.gxl" class="-1"/>
	<graph file="benzo[c]pentaphene.gxl" class="-1"/>
	<graph file="naphtho[1,2-b]triphenylene.gxl" class="-1"/>
	<graph file="pyrene.gxl" class="-1"/>
	<graph file="pentacene.gxl" class="-1"/>
	<graph file="2-methylbenz[a]anthracene.gxl" class="-1"/>
	<graph file="phenanthrene.gxl" class="-1"/>
	<graph file="benzo[b]chrysene.gxl" class="-1"/>
	<graph file="2-methylpyrene.gxl" class="-1"/>
	<graph file="dibenzo[b,g]phenanthrene.gxl" class="-1"/>
	<graph file="anthra[1,2-a]anthracene.gxl" class="-1"/>
	<graph file="8-methylbenzo[a]pyrene.gxl" class="-1"/>
	<graph file="benzo[a]naphthacene.gxl" class="-1"/>
	<graph file="anthracene.gxl" class="-1"/>
	<graph file="5-methylbenz[a]anthracene.gxl" class="-1"/>
	<graph file="3-methylbenz[a]anthracene.gxl" class="-1"/>
	<graph file="perylene.gxl" class="-1"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/median/collections/Letter_150.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="AP1_0099.gxl" class="A"/>
	<graph file="AP1_0079.gxl" class="A"/>
	<graph file="AP1_0127.gxl" class="A"/>
	<graph file="AP1_0013.gxl" class="A"/>
	<graph file="AP1_0044.gxl" class="A"/>
	<graph file="AP1_0104.gxl" class="A"/>
	<graph file="AP1_0038.gxl" class="A"/>
	<graph file="AP1_0148.gxl" class="A"/>
	<graph file="AP1_0134.gxl" class="A"/>
	<graph file="AP1_0139.gxl" class="A"/>
	<graph file="EP1_0051.gxl" class="E"/>
	<graph file="EP1_0062.gxl" class="E"/>
	<graph file="EP1_0006.gxl" class="E"/>
	<graph file="EP1_0042.gxl" class="E"/>
	<graph file="EP1_0111.gxl" class="E"/>
	<graph file="EP1_0038.gxl" class="E"/>
	<graph file="EP1_0126.gxl" class="E"/>
	<graph file="EP1_0096.gxl" class="E"/>
	<graph file="EP1_0027.gxl" class="E"/>
	<graph file="EP1_0030.gxl" class="E"/>
	<graph file="FP1_0111.gxl" class="F"/>
	<graph file="FP1_0038.gxl" class="F"/>
	<graph file="FP1_0112.gxl" class="F"/>
	<graph file="FP1_0105.gxl" class="F"/>
	<graph file="FP1_0136.gxl" class="F"/>
	<graph file="FP1_0044.gxl" class="F"/>
	<graph file="FP1_0080.gxl" class="F"/>
	<graph file="FP1_0039.gxl" class="F"/>
	<graph file="FP1_0018.gxl" class="F"/>
	<graph file="FP1_0049.gxl" class="F"/>
	<graph file="IP1_0117.gxl" class="I"/>
	<graph file="IP1_0128.gxl" class="I"/>
	<graph file="IP1_0144.gxl" class="I"/>
	<graph file="IP1_0032.gxl" class="I"/>
	<graph file="IP1_0039.gxl" class="I"/>
	<graph file="IP1_0067.gxl" class="I"/>
	<graph file="IP1_0090.gxl" class="I"/>
	<graph file="IP1_0133.gxl" class="I"/>
	<graph file="IP1_0028.gxl" class="I"/>
	<graph file="IP1_0007.gxl" class="I"/>
	<graph file="HP1_0126.gxl" class="H"/>
	<graph file="HP1_0128.gxl" class="H"/>
	<graph file="HP1_0103.gxl" class="H"/>
	<graph file="HP1_0015.gxl" class="H"/>
	<graph file="HP1_0130.gxl" class="H"/>
	<graph file="HP1_0013.gxl" class="H"/>
	<graph file="HP1_0028.gxl" class="H"/>
	<graph file="HP1_0051.gxl" class="H"/>
	<graph file="HP1_0005.gxl" class="H"/>
	<graph file="HP1_0149.gxl" class="H"/>
	<graph file="KP1_0125.gxl" class="K"/>
	<graph file="KP1_0146.gxl" class="K"/>
	<graph file="KP1_0003.gxl" class="K"/>
	<graph file="KP1_0068.gxl" class="K"/>
	<graph file="KP1_0091.gxl" class="K"/>
	<graph file="KP1_0120.gxl" class="K"/>
	<graph file="KP1_0018.gxl" class="K"/>
	<graph file="KP1_0070.gxl" class="K"/>
	<graph file="KP1_0088.gxl" class="K"/>
	<graph file="KP1_0082.gxl" class="K"/>
	<graph file="MP1_0124.gxl" class="M"/>
	<graph file="MP1_0113.gxl" class="M"/>
	<graph file="MP1_0048.gxl" class="M"/>
	<graph file="MP1_0021.gxl" class="M"/>
	<graph file="MP1_0125.gxl" class="M"/>
	<graph file="MP1_0129.gxl" class="M"/>
	<graph file="MP1_0020.gxl" class="M"/>
	<graph file="MP1_0000.gxl" class="M"/>
	<graph file="MP1_0041.gxl" class="M"/>
	<graph file="MP1_0070.gxl" class="M"/>
	<graph file="LP1_0145.gxl" class="L"/>
	<graph file="LP1_0133.gxl" class="L"/>
	<graph file="LP1_0010.gxl" class="L"/>
	<graph file="LP1_0036.gxl" class="L"/>
	<graph file="LP1_0100.gxl" class="L"/>
	<graph file="LP1_0094.gxl" class="L"/>
	<graph file="LP1_0002.gxl" class="L"/>
	<graph file="LP1_0117.gxl" class="L"/>
	<graph file="LP1_0026.gxl" class="L"/>
	<graph file="LP1_0029.gxl" class="L"/>
	<graph file="NP1_0027.gxl" class="N"/>
	<graph file="NP1_0036.gxl" class="N"/>
	<graph file="NP1_0046.gxl" class="N"/>
	<graph file="NP1_0042.gxl" class="N"/>
	<graph file="NP1_0088.gxl" class="N"/>
	<graph file="NP1_0038.gxl" class="N"/>
	<graph file="NP1_0129.gxl" class="N"/>
	<graph file="NP1_0053.gxl" class="N"/>
	<graph file="NP1_0052.gxl" class="N"/>
	<graph file="NP1_0039.gxl" class="N"/>
	<graph file="TP1_0103.gxl" class="T"/>
	<graph file="TP1_0068.gxl" class="T"/>
	<graph file="TP1_0049.gxl" class="T"/>
	<graph file="TP1_0126.gxl" class="T"/>
	<graph file="TP1_0016.gxl" class="T"/>
	<graph file="TP1_0138.gxl" class="T"/>
	<graph file="TP1_0074.gxl" class="T"/>
	<graph file="TP1_0134.gxl" class="T"/>
	<graph file="TP1_0025.gxl" class="T"/>
	<graph file="TP1_0102.gxl" class="T"/>
	<graph file="WP1_0049.gxl" class="W"/>
	<graph file="WP1_0118.gxl" class="W"/>
	<graph file="WP1_0104.gxl" class="W"/>
	<graph file="WP1_0111.gxl" class="W"/>
	<graph file="WP1_0075.gxl" class="W"/>
	<graph file="WP1_0036.gxl" class="W"/>
	<graph file="WP1_0087.gxl" class="W"/>
	<graph file="WP1_0054.gxl" class="W"/>
	<graph file="WP1_0078.gxl" class="W"/>
	<graph file="WP1_0050.gxl" class="W"/>
	<graph file="VP1_0011.gxl" class="V"/>
	<graph file="VP1_0060.gxl" class="V"/>
	<graph file="VP1_0092.gxl" class="V"/>
	<graph file="VP1_0056.gxl" class="V"/>
	<graph file="VP1_0049.gxl" class="V"/>
	<graph file="VP1_0134.gxl" class="V"/>
	<graph file="VP1_0119.gxl" class="V"/>
	<graph file="VP1_0029.gxl" class="V"/>
	<graph file="VP1_0020.gxl" class="V"/>
	<graph file="VP1_0109.gxl" class="V"/>
	<graph file="YP1_0045.gxl" class="Y"/>
	<graph file="YP1_0060.gxl" class="Y"/>
	<graph file="YP1_0003.gxl" class="Y"/>
	<graph file="YP1_0074.gxl" class="Y"/>
	<graph file="YP1_0110.gxl" class="Y"/>
	<graph file="YP1_0079.gxl" class="Y"/>
	<graph file="YP1_0024.gxl" class="Y"/>
	<graph file="YP1_0071.gxl" class="Y"/>
	<graph file="YP1_0038.gxl" class="Y"/>
	<graph file="YP1_0130.gxl" class="Y"/>
	<graph file="XP1_0067.gxl" class="X"/>
	<graph file="XP1_0095.gxl" class="X"/>
	<graph file="XP1_0148.gxl" class="X"/>
	<graph file="XP1_0099.gxl" class="X"/>
	<graph file="XP1_0128.gxl" class="X"/>
	<graph file="XP1_0117.gxl" class="X"/>
	<graph file="XP1_0049.gxl" class="X"/>
	<graph file="XP1_0038.gxl" class="X"/>
	<graph file="XP1_0016.gxl" class="X"/>
	<graph file="XP1_0141.gxl" class="X"/>
	<graph file="ZP1_0009.gxl" class="Z"/>
	<graph file="ZP1_0076.gxl" class="Z"/>
	<graph file="ZP1_0097.gxl" class="Z"/>
	<graph file="ZP1_0021.gxl" class="Z"/>
	<graph file="ZP1_0101.gxl" class="Z"/>
	<graph file="ZP1_0044.gxl" class="Z"/>
	<graph file="ZP1_0073.gxl" class="Z"/>
	<graph file="ZP1_0003.gxl" class="Z"/>
	<graph file="ZP1_0096.gxl" class="Z"/>
	<graph file="ZP1_0116.gxl" class="Z"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/tests/ijprai2020/collections/S-MOL_100.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
<graph file="molecule_50.gxl" class="a"/>
<graph file="molecule_51.gxl" class="a"/>
<graph file="molecule_52.gxl" class="a"/>
<graph file="molecule_53.gxl" class="a"/>
<graph file="molecule_54.gxl" class="a"/>
<graph file="molecule_55.gxl" class="a"/>
<graph file="molecule_56.gxl" class="a"/>
<graph file="molecule_57.gxl" class="a"/>
<graph file="molecule_58.gxl" class="a"/>
<graph file="molecule_59.gxl" class="a"/>
<graph file="molecule_60.gxl" class="a"/>
<graph file="molecule_61.gxl" class="a"/>
<graph file="molecule_62.gxl" class="a"/>
<graph file="molecule_63.gxl" class="a"/>
<graph file="molecule_64.gxl" class="a"/>
<graph file="molecule_65.gxl" class="a"/>
<graph file="molecule_66.gxl" class="a"/>
<graph file="molecule_67.gxl" class="a"/>
<graph file="molecule_68.gxl" class="a"/>
<graph file="molecule_69.gxl" class="a"/>
<graph file="molecule_70.gxl" class="a"/>
<graph file="molecule_71.gxl" class="a"/>
<graph file="molecule_72.gxl" class="a"/>
<graph file="molecule_73.gxl" class="a"/>
<graph file="molecule_74.gxl" class="a"/>
<graph file="molecule_75.gxl" class="a"/>
<graph file="molecule_76.gxl" class="a"/>
<graph file="molecule_77.gxl" class="a"/>
<graph file="molecule_78.gxl" class="a"/>
<graph file="molecule_79.gxl" class="a"/>
<graph file="molecule_80.gxl" class="a"/>
<graph file="molecule_81.gxl" class="a"/>
<graph file="molecule_82.gxl" class="a"/>
<graph file="molecule_83.gxl" class="a"/>
<graph file="molecule_84.gxl" class="a"/>
<graph file="molecule_85.gxl" class="a"/>
<graph file="molecule_86.gxl" class="a"/>
<graph file="molecule_87.gxl" class="a"/>
<graph file="molecule_88.gxl" class="a"/>
<graph file="molecule_89.gxl" class="a"/>
<graph file="molecule_90.gxl" class="a"/>
<graph file="molecule_91.gxl" class="a"/>
<graph file="molecule_92.gxl" class="a"/>
<graph file="molecule_93.gxl" class="a"/>
<graph file="molecule_94.gxl" class="a"/>
<graph file="molecule_95.gxl" class="a"/>
<graph file="molecule_96.gxl" class="a"/>
<graph file="molecule_97.gxl" class="a"/>
<graph file="molecule_98.gxl" class="a"/>
<graph file="molecule_99.gxl" class="a"/>
<graph file="molecule_100.gxl" class="a"/>
<graph file="molecule_101.gxl" class="a"/>
<graph file="molecule_102.gxl" class="a"/>
<graph file="molecule_103.gxl" class="a"/>
<graph file="molecule_104.gxl" class="a"/>
<graph file="molecule_105.gxl" class="a"/>
<graph file="molecule_106.gxl" class="a"/>
<graph file="molecule_107.gxl" class="a"/>
<graph file="molecule_108.gxl" class="a"/>
<graph file="molecule_109.gxl" class="a"/>
<graph file="molecule_110.gxl" class="a"/>
<graph file="molecule_111.gxl" class="a"/>
<graph file="molecule_112.gxl" class="a"/>
<graph file="molecule_113.gxl" class="a"/>
<graph file="molecule_114.gxl" class="a"/>
<graph file="molecule_115.gxl" class="a"/>
<graph file="molecule_116.gxl" class="a"/>
<graph file="molecule_117.gxl" class="a"/>
<graph file="molecule_118.gxl" class="a"/>
<graph file="molecule_119.gxl" class="a"/>
<graph file="molecule_120.gxl" class="a"/>
<graph file="molecule_121.gxl" class="a"/>
<graph file="molecule_122.gxl" class="a"/>
<graph file="molecule_123.gxl" class="a"/>
<graph file="molecule_124.gxl" class="a"/>
<graph file="molecule_125.gxl" class="a"/>
<graph file="molecule_126.gxl" class="a"/>
<graph file="molecule_127.gxl" class="a"/>
<graph file="molecule_128.gxl" class="a"/>
<graph file="molecule_129.gxl" class="a"/>
<graph file="molecule_130.gxl" class="a"/>
<graph file="molecule_131.gxl" class="a"/>
<graph file="molecule_132.gxl" class="a"/>
<graph file="molecule_133.gxl" class="a"/>
<graph file="molecule_134.gxl" class="a"/>
<graph file="molecule_135.gxl" class="a"/>
<graph file="molecule_136.gxl" class="a"/>
<graph file="molecule_137.gxl" class="a"/>
<graph file="molecule_138.gxl" class="a"/>
<graph file="molecule_139.gxl" class="a"/>
<graph file="molecule_140.gxl" class="a"/>
<graph file="molecule_141.gxl" class="a"/>
<graph file="molecule_142.gxl" class="a"/>
<graph file="molecule_143.gxl" class="a"/>
<graph file="molecule_144.gxl" class="a"/>
<graph file="molecule_145.gxl" class="a"/>
<graph file="molecule_146.gxl" class="a"/>
<graph file="molecule_147.gxl" class="a"/>
<graph file="molecule_148.gxl" class="a"/>
<graph file="molecule_149.gxl" class="a"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/tests/vldbj2020/collections/AIDS21-30.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="11059.gxl" class="a"/>
	<graph file="11108.gxl" class="a"/>
	<graph file="18434.gxl" class="a"/>
	<graph file="18350.gxl" class="a"/>
	<graph file="33065.gxl" class="a"/>
	<graph file="22710.gxl" class="a"/>
	<graph file="21992.gxl" class="a"/>
	<graph file="41803.gxl" class="a"/>
	<graph file="20076.gxl" class="a"/>
	<graph file="41804.gxl" class="a"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/tests/ijprai2020/collections/Fingerprint_50.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="s1060_05.gxl" class="A "/>
	<graph file="s1933_01.gxl" class="A "/>
	<graph file="f1496_10.gxl" class="A "/>
	<graph file="f0215_01.gxl" class="A "/>
	<graph file="s1586_05.gxl" class="A "/>
	<graph file="f0190_08.gxl" class="A "/>
	<graph file="s1731_04.gxl" class="A "/>
	<graph file="f0230_10.gxl" class="A "/>
	<graph file="f0005_03.gxl" class="A "/>
	<graph file="f1614_09.gxl" class="L "/>
	<graph file="s1105_08.gxl" class="L "/>
	<graph file="s1048_06.gxl" class="L "/>
	<graph file="s0203_10.gxl" class="L "/>
	<graph file="f1247_06.gxl" class="L "/>
	<graph file="f1532_07.gxl" class="L "/>
	<graph file="s1169_07.gxl" class="L "/>
	<graph file="s0534_08.gxl" class="L "/>
	<graph file="f0656_06.gxl" class="L "/>
	<graph file="f1914_05.gxl" class="W "/>
	<graph file="f1459_09.gxl" class="W "/>
	<graph file="s1394_07.gxl" class="W "/>
	<graph file="s1467_09.gxl" class="W "/>
	<graph file="f0533_04.gxl" class="W "/>
	<graph file="s0519_06.gxl" class="W "/>
	<graph file="s1739_01.gxl" class="W "/>
	<graph file="s1863_04.gxl" class="W "/>
	<graph file="f1786_05.gxl" class="W "/>
	<graph file="s1733_02.gxl" class="TR"/>
	<graph file="s0039_03.gxl" class="TR"/>
	<graph file="f1726_02.gxl" class="TR"/>
	<graph file="f1634_09.gxl" class="TL"/>
	<graph file="s1928_02.gxl" class="TL"/>
	<graph file="f1195_01.gxl" class="R "/>
	<graph file="f1889_04.gxl" class="R "/>
	<graph file="s1125_01.gxl" class="R "/>
	<graph file="f1421_04.gxl" class="R "/>
	<graph file="s0157_03.gxl" class="R "/>
	<graph file="f1935_04.gxl" class="R "/>
	<graph file="s1516_02.gxl" class="R "/>
	<graph file="f0068_01.gxl" class="R "/>
	<graph file="s1043_01.gxl" class="R "/>
	<graph file="f0648_07.gxl" class="T "/>
	<graph file="f1275_02.gxl" class="T "/>
	<graph file="f0560_08.gxl" class="TA"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/tests/vldbj2020/collections/Protein11-20.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="enzyme_330.gxl" class="4"/>
	<graph file="enzyme_565.gxl" class="6"/>
	<graph file="enzyme_96.gxl" class="1"/>
	<graph file="enzyme_188.gxl" class="2"/>
	<graph file="enzyme_398.gxl" class="4"/>
	<graph file="enzyme_110.gxl" class="2"/>
	<graph file="enzyme_106.gxl" class="2"/>
	<graph file="enzyme_144.gxl" class="2"/>
	<graph file="enzyme_145.gxl" class="2"/>
	<graph file="enzyme_53.gxl" class="1"/>
</GraphCollection>
