=== michaelflppv/mixup/gedlib/data/collections/GraphCollection.dtd
<!-- 

GraphCollection
Document Type Definition  

This file is part of GEDLIB (1.0)

-->

<!ELEMENT GraphCollection (graph+)>
<!ELEMENT graph EMPTY>
<!ATTLIST graph file ID #REQUIRED>
<!ATTLIST graph class CDATA #REQUIRED>

=== michaelflppv/mixup/gedlib/median/collections/Letter_X.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="XP1_0050.gxl" class="X"/>
	<graph file="XP1_0051.gxl" class="X"/>
	<graph file="XP1_0052.gxl" class="X"/>
	<graph file="XP1_0053.gxl" class="X"/>
	<graph file="XP1_0054.gxl" class="X"/>
	<graph file="XP1_0055.gxl" class="X"/>
	<graph file="XP1_0056.gxl" class="X"/>
	<graph file="XP1_0057.gxl" class="X"/>
	<graph file="XP1_0058.gxl" class="X"/>
	<graph file="XP1_0059.gxl" class="X"/>
	<graph file="XP1_0060.gxl" class="X"/>
	<graph file="XP1_0061.gxl" class="X"/>
	<graph file="XP1_0062.gxl" class="X"/>
	<graph file="XP1_0063.gxl" class="X"/>
	<graph file="XP1_0064.gxl" class="X"/>
	<graph file="XP1_0065.gxl" class="X"/>
	<graph file="XP1_0066.gxl" class="X"/>
	<graph file="XP1_0067.gxl" class="X"/>
	<graph file="XP1_0068.gxl" class="X"/>
	<graph file="XP1_0069.gxl" class="X"/>
	<graph file="XP1_0070.gxl" class="X"/>
	<graph file="XP1_0071.gxl" class="X"/>
	<graph file="XP1_0072.gxl" class="X"/>
	<graph file="XP1_0073.gxl" class="X"/>
	<graph file="XP1_0074.gxl" class="X"/>
	<graph file="XP1_0075.gxl" class="X"/>
	<graph file="XP1_0076.gxl" class="X"/>
	<graph file="XP1_0077.gxl" class="X"/>
	<graph file="XP1_0078.gxl" class="X"/>
	<graph file="XP1_0079.gxl" class="X"/>
	<graph file="XP1_0080.gxl" class="X"/>
	<graph file="XP1_0081.gxl" class="X"/>
	<graph file="XP1_0082.gxl" class="X"/>
	<graph file="XP1_0083.gxl" class="X"/>
	<graph file="XP1_0084.gxl" class="X"/>
	<graph file="XP1_0085.gxl" class="X"/>
	<graph file="XP1_0086.gxl" class="X"/>
	<graph file="XP1_0087.gxl" class="X"/>
	<graph file="XP1_0088.gxl" class="X"/>
	<graph file="XP1_0089.gxl" class="X"/>
	<graph file="XP1_0090.gxl" class="X"/>
	<graph file="XP1_0091.gxl" class="X"/>
	<graph file="XP1_0092.gxl" class="X"/>
	<graph file="XP1_0093.gxl" class="X"/>
	<graph file="XP1_0094.gxl" class="X"/>
	<graph file="XP1_0095.gxl" class="X"/>
	<graph file="XP1_0096.gxl" class="X"/>
	<graph file="XP1_0097.gxl" class="X"/>
	<graph file="XP1_0098.gxl" class="X"/>
	<graph file="XP1_0099.gxl" class="X"/>
	<graph file="XP1_0000.gxl" class="X"/>
	<graph file="XP1_0001.gxl" class="X"/>
	<graph file="XP1_0002.gxl" class="X"/>
	<graph file="XP1_0003.gxl" class="X"/>
	<graph file="XP1_0004.gxl" class="X"/>
	<graph file="XP1_0005.gxl" class="X"/>
	<graph file="XP1_0006.gxl" class="X"/>
	<graph file="XP1_0007.gxl" class="X"/>
	<graph file="XP1_0008.gxl" class="X"/>
	<graph file="XP1_0009.gxl" class="X"/>
	<graph file="XP1_0010.gxl" class="X"/>
	<graph file="XP1_0011.gxl" class="X"/>
	<graph file="XP1_0012.gxl" class="X"/>
	<graph file="XP1_0013.gxl" class="X"/>
	<graph file="XP1_0014.gxl" class="X"/>
	<graph file="XP1_0015.gxl" class="X"/>
	<graph file="XP1_0016.gxl" class="X"/>
	<graph file="XP1_0017.gxl" class="X"/>
	<graph file="XP1_0018.gxl" class="X"/>
	<graph file="XP1_0019.gxl" class="X"/>
	<graph file="XP1_0020.gxl" class="X"/>
	<graph file="XP1_0021.gxl" class="X"/>
	<graph file="XP1_0022.gxl" class="X"/>
	<graph file="XP1_0023.gxl" class="X"/>
	<graph file="XP1_0024.gxl" class="X"/>
	<graph file="XP1_0025.gxl" class="X"/>
	<graph file="XP1_0026.gxl" class="X"/>
	<graph file="XP1_0027.gxl" class="X"/>
	<graph file="XP1_0028.gxl" class="X"/>
	<graph file="XP1_0029.gxl" class="X"/>
	<graph file="XP1_0030.gxl" class="X"/>
	<graph file="XP1_0031.gxl" class="X"/>
	<graph file="XP1_0032.gxl" class="X"/>
	<graph file="XP1_0033.gxl" class="X"/>
	<graph file="XP1_0034.gxl" class="X"/>
	<graph file="XP1_0035.gxl" class="X"/>
	<graph file="XP1_0036.gxl" class="X"/>
	<graph file="XP1_0037.gxl" class="X"/>
	<graph file="XP1_0038.gxl" class="X"/>
	<graph file="XP1_0039.gxl" class="X"/>
	<graph file="XP1_0040.gxl" class="X"/>
	<graph file="XP1_0041.gxl" class="X"/>
	<graph file="XP1_0042.gxl" class="X"/>
	<graph file="XP1_0043.gxl" class="X"/>
	<graph file="XP1_0044.gxl" class="X"/>
	<graph file="XP1_0045.gxl" class="X"/>
	<graph file="XP1_0046.gxl" class="X"/>
	<graph file="XP1_0047.gxl" class="X"/>
	<graph file="XP1_0048.gxl" class="X"/>
	<graph file="XP1_0049.gxl" class="X"/>
	<graph file="XP1_0100.gxl" class="X"/>
	<graph file="XP1_0101.gxl" class="X"/>
	<graph file="XP1_0102.gxl" class="X"/>
	<graph file="XP1_0103.gxl" class="X"/>
	<graph file="XP1_0104.gxl" class="X"/>
	<graph file="XP1_0105.gxl" class="X"/>
	<graph file="XP1_0106.gxl" class="X"/>
	<graph file="XP1_0107.gxl" class="X"/>
	<graph file="XP1_0108.gxl" class="X"/>
	<graph file="XP1_0109.gxl" class="X"/>
	<graph file="XP1_0110.gxl" class="X"/>
	<graph file="XP1_0111.gxl" class="X"/>
	<graph file="XP1_0112.gxl" class="X"/>
	<graph file="XP1_0113.gxl" class="X"/>
	<graph file="XP1_0114.gxl" class="X"/>
	<graph file="XP1_0115.gxl" class="X"/>
	<graph file="XP1_0116.gxl" class="X"/>
	<graph file="XP1_0117.gxl" class="X"/>
	<graph file="XP1_0118.gxl" class="X"/>
	<graph file="XP1_0119.gxl" class="X"/>
	<graph file="XP1_0120.gxl" class="X"/>
	<graph file="XP1_0121.gxl" class="X"/>
	<graph file="XP1_0122.gxl" class="X"/>
	<graph file="XP1_0123.gxl" class="X"/>
	<graph file="XP1_0124.gxl" class="X"/>
	<graph file="XP1_0125.gxl" class="X"/>
	<graph file="XP1_0126.gxl" class="X"/>
	<graph file="XP1_0127.gxl" class="X"/>
	<graph file="XP1_0128.gxl" class="X"/>
	<graph file="XP1_0129.gxl" class="X"/>
	<graph file="XP1_0130.gxl" class="X"/>
	<graph file="XP1_0131.gxl" class="X"/>
	<graph file="XP1_0132.gxl" class="X"/>
	<graph file="XP1_0133.gxl" class="X"/>
	<graph file="XP1_0134.gxl" class="X"/>
	<graph file="XP1_0135.gxl" class="X"/>
	<graph file="XP1_0136.gxl" class="X"/>
	<graph file="XP1_0137.gxl" class="X"/>
	<graph file="XP1_0138.gxl" class="X"/>
	<graph file="XP1_0139.gxl" class="X"/>
	<graph file="XP1_0140.gxl" class="X"/>
	<graph file="XP1_0141.gxl" class="X"/>
	<graph file="XP1_0142.gxl" class="X"/>
	<graph file="XP1_0143.gxl" class="X"/>
	<graph file="XP1_0144.gxl" class="X"/>
	<graph file="XP1_0145.gxl" class="X"/>
	<graph file="XP1_0146.gxl" class="X"/>
	<graph file="XP1_0147.gxl" class="X"/>
	<graph file="XP1_0148.gxl" class="X"/>
	<graph file="XP1_0149.gxl" class="X"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/median/collections/Letter_A.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="AP1_0050.gxl" class="A"/>
	<graph file="AP1_0051.gxl" class="A"/>
	<graph file="AP1_0052.gxl" class="A"/>
	<graph file="AP1_0053.gxl" class="A"/>
	<graph file="AP1_0054.gxl" class="A"/>
	<graph file="AP1_0055.gxl" class="A"/>
	<graph file="AP1_0056.gxl" class="A"/>
	<graph file="AP1_0057.gxl" class="A"/>
	<graph file="AP1_0058.gxl" class="A"/>
	<graph file="AP1_0059.gxl" class="A"/>
	<graph file="AP1_0060.gxl" class="A"/>
	<graph file="AP1_0061.gxl" class="A"/>
	<graph file="AP1_0062.gxl" class="A"/>
	<graph file="AP1_0063.gxl" class="A"/>
	<graph file="AP1_0064.gxl" class="A"/>
	<graph file="AP1_0065.gxl" class="A"/>
	<graph file="AP1_0066.gxl" class="A"/>
	<graph file="AP1_0067.gxl" class="A"/>
	<graph file="AP1_0068.gxl" class="A"/>
	<graph file="AP1_0069.gxl" class="A"/>
	<graph file="AP1_0070.gxl" class="A"/>
	<graph file="AP1_0071.gxl" class="A"/>
	<graph file="AP1_0072.gxl" class="A"/>
	<graph file="AP1_0073.gxl" class="A"/>
	<graph file="AP1_0074.gxl" class="A"/>
	<graph file="AP1_0075.gxl" class="A"/>
	<graph file="AP1_0076.gxl" class="A"/>
	<graph file="AP1_0077.gxl" class="A"/>
	<graph file="AP1_0078.gxl" class="A"/>
	<graph file="AP1_0079.gxl" class="A"/>
	<graph file="AP1_0080.gxl" class="A"/>
	<graph file="AP1_0081.gxl" class="A"/>
	<graph file="AP1_0082.gxl" class="A"/>
	<graph file="AP1_0083.gxl" class="A"/>
	<graph file="AP1_0084.gxl" class="A"/>
	<graph file="AP1_0085.gxl" class="A"/>
	<graph file="AP1_0086.gxl" class="A"/>
	<graph file="AP1_0087.gxl" class="A"/>
	<graph file="AP1_0088.gxl" class="A"/>
	<graph file="AP1_0089.gxl" class="A"/>
	<graph file="AP1_0090.gxl" class="A"/>
	<graph file="AP1_0091.gxl" class="A"/>
	<graph file="AP1_0092.gxl" class="A"/>
	<graph file="AP1_0093.gxl" class="A"/>
	<graph file="AP1_0094.gxl" class="A"/>
	<graph file="AP1_0095.gxl" class="A"/>
	<graph file="AP1_0096.gxl" class="A"/>
	<graph file="AP1_0097.gxl" class="A"/>
	<graph file="AP1_0098.gxl" class="A"/>
	<graph file="AP1_0099.gxl" class="A"/>
	<graph file="AP1_0000.gxl" class="A"/>
	<graph file="AP1_0001.gxl" class="A"/>
	<graph file="AP1_0002.gxl" class="A"/>
	<graph file="AP1_0003.gxl" class="A"/>
	<graph file="AP1_0004.gxl" class="A"/>
	<graph file="AP1_0005.gxl" class="A"/>
	<graph file="AP1_0006.gxl" class="A"/>
	<graph file="AP1_0007.gxl" class="A"/>
	<graph file="AP1_0008.gxl" class="A"/>
	<graph file="AP1_0009.gxl" class="A"/>
	<graph file="AP1_0010.gxl" class="A"/>
	<graph file="AP1_0011.gxl" class="A"/>
	<graph file="AP1_0012.gxl" class="A"/>
	<graph file="AP1_0013.gxl" class="A"/>
	<graph file="AP1_0014.gxl" class="A"/>
	<graph file="AP1_0015.gxl" class="A"/>
	<graph file="AP1_0016.gxl" class="A"/>
	<graph file="AP1_0017.gxl" class="A"/>
	<graph file="AP1_0018.gxl" class="A"/>
	<graph file="AP1_0019.gxl" class="A"/>
	<graph file="AP1_0020.gxl" class="A"/>
	<graph file="AP1_0021.gxl" class="A"/>
	<graph file="AP1_0022.gxl" class="A"/>
	<graph file="AP1_0023.gxl" class="A"/>
	<graph file="AP1_0024.gxl" class="A"/>
	<graph file="AP1_0025.gxl" class="A"/>
	<graph file="AP1_0026.gxl" class="A"/>
	<graph file="AP1_0027.gxl" class="A"/>
	<graph file="AP1_0028.gxl" class="A"/>
	<graph file="AP1_0029.gxl" class="A"/>
	<graph file="AP1_0030.gxl" class="A"/>
	<graph file="AP1_0031.gxl" class="A"/>
	<graph file="AP1_0032.gxl" class="A"/>
	<graph file="AP1_0033.gxl" class="A"/>
	<graph file="AP1_0034.gxl" class="A"/>
	<graph file="AP1_0035.gxl" class="A"/>
	<graph file="AP1_0036.gxl" class="A"/>
	<graph file="AP1_0037.gxl" class="A"/>
	<graph file="AP1_0038.gxl" class="A"/>
	<graph file="AP1_0039.gxl" class="A"/>
	<graph file="AP1_0040.gxl" class="A"/>
	<graph file="AP1_0041.gxl" class="A"/>
	<graph file="AP1_0042.gxl" class="A"/>
	<graph file="AP1_0043.gxl" class="A"/>
	<graph file="AP1_0044.gxl" class="A"/>
	<graph file="AP1_0045.gxl" class="A"/>
	<graph file="AP1_0046.gxl" class="A"/>
	<graph file="AP1_0047.gxl" class="A"/>
	<graph file="AP1_0048.gxl" class="A"/>
	<graph file="AP1_0049.gxl" class="A"/>
	<graph file="AP1_0100.gxl" class="A"/>
	<graph file="AP1_0101.gxl" class="A"/>
	<graph file="AP1_0102.gxl" class="A"/>
	<graph file="AP1_0103.gxl" class="A"/>
	<graph file="AP1_0104.gxl" class="A"/>
	<graph file="AP1_0105.gxl" class="A"/>
	<graph file="AP1_0106.gxl" class="A"/>
	<graph file="AP1_0107.gxl" class="A"/>
	<graph file="AP1_0108.gxl" class="A"/>
	<graph file="AP1_0109.gxl" class="A"/>
	<graph file="AP1_0110.gxl" class="A"/>
	<graph file="AP1_0111.gxl" class="A"/>
	<graph file="AP1_0112.gxl" class="A"/>
	<graph file="AP1_0113.gxl" class="A"/>
	<graph file="AP1_0114.gxl" class="A"/>
	<graph file="AP1_0115.gxl" class="A"/>
	<graph file="AP1_0116.gxl" class="A"/>
	<graph file="AP1_0117.gxl" class="A"/>
	<graph file="AP1_0118.gxl" class="A"/>
	<graph file="AP1_0119.gxl" class="A"/>
	<graph file="AP1_0120.gxl" class="A"/>
	<graph file="AP1_0121.gxl" class="A"/>
	<graph file="AP1_0122.gxl" class="A"/>
	<graph file="AP1_0123.gxl" class="A"/>
	<graph file="AP1_0124.gxl" class="A"/>
	<graph file="AP1_0125.gxl" class="A"/>
	<graph file="AP1_0126.gxl" class="A"/>
	<graph file="AP1_0127.gxl" class="A"/>
	<graph file="AP1_0128.gxl" class="A"/>
	<graph file="AP1_0129.gxl" class="A"/>
	<graph file="AP1_0130.gxl" class="A"/>
	<graph file="AP1_0131.gxl" class="A"/>
	<graph file="AP1_0132.gxl" class="A"/>
	<graph file="AP1_0133.gxl" class="A"/>
	<graph file="AP1_0134.gxl" class="A"/>
	<graph file="AP1_0135.gxl" class="A"/>
	<graph file="AP1_0136.gxl" class="A"/>
	<graph file="AP1_0137.gxl" class="A"/>
	<graph file="AP1_0138.gxl" class="A"/>
	<graph file="AP1_0139.gxl" class="A"/>
	<graph file="AP1_0140.gxl" class="A"/>
	<graph file="AP1_0141.gxl" class="A"/>
	<graph file="AP1_0142.gxl" class="A"/>
	<graph file="AP1_0143.gxl" class="A"/>
	<graph file="AP1_0144.gxl" class="A"/>
	<graph file="AP1_0145.gxl" class="A"/>
	<graph file="AP1_0146.gxl" class="A"/>
	<graph file="AP1_0147.gxl" class="A"/>
	<graph file="AP1_0148.gxl" class="A"/>
	<graph file="AP1_0149.gxl" class="A"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/tests/ijprai2020/collections/alkane_50.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="molecule001.gxl" class="a"/>
	<graph file="molecule002.gxl" class="a"/>
	<graph file="molecule003.gxl" class="a"/>
	<graph file="molecule004.gxl" class="a"/>
	<graph file="molecule005.gxl" class="a"/>
	<graph file="molecule006.gxl" class="a"/>
	<graph file="molecule007.gxl" class="a"/>
	<graph file="molecule008.gxl" class="a"/>
	<graph file="molecule009.gxl" class="a"/>
	<graph file="molecule010.gxl" class="a"/>
	<graph file="molecule011.gxl" class="a"/>
	<graph file="molecule012.gxl" class="a"/>
	<graph file="molecule013.gxl" class="a"/>
	<graph file="molecule014.gxl" class="a"/>
	<graph file="molecule015.gxl" class="a"/>
	<graph file="molecule016.gxl" class="a"/>
	<graph file="molecule017.gxl" class="a"/>
	<graph file="molecule018.gxl" class="a"/>
	<graph file="molecule019.gxl" class="a"/>
	<graph file="molecule020.gxl" class="a"/>
	<graph file="molecule021.gxl" class="a"/>
	<graph file="molecule022.gxl" class="a"/>
	<graph file="molecule023.gxl" class="a"/>
	<graph file="molecule024.gxl" class="a"/>
	<graph file="molecule025.gxl" class="a"/>
	<graph file="molecule026.gxl" class="a"/>
	<graph file="molecule027.gxl" class="a"/>
	<graph file="molecule028.gxl" class="a"/>
	<graph file="molecule029.gxl" class="a"/>
	<graph file="molecule030.gxl" class="a"/>
	<graph file="molecule031.gxl" class="a"/>
	<graph file="molecule032.gxl" class="a"/>
	<graph file="molecule033.gxl" class="a"/>
	<graph file="molecule034.gxl" class="a"/>
	<graph file="molecule035.gxl" class="a"/>
	<graph file="molecule036.gxl" class="a"/>
	<graph file="molecule037.gxl" class="a"/>
	<graph file="molecule038.gxl" class="a"/>
	<graph file="molecule039.gxl" class="a"/>
	<graph file="molecule040.gxl" class="a"/>
	<graph file="molecule041.gxl" class="a"/>
	<graph file="molecule042.gxl" class="a"/>
	<graph file="molecule043.gxl" class="a"/>
	<graph file="molecule044.gxl" class="a"/>
	<graph file="molecule045.gxl" class="a"/>
	<graph file="molecule046.gxl" class="a"/>
	<graph file="molecule047.gxl" class="a"/>
	<graph file="molecule048.gxl" class="a"/>
	<graph file="molecule049.gxl" class="a"/>
	<graph file="molecule050.gxl" class="a"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/median/collections/Letter_F.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="FP1_0050.gxl" class="F"/>
	<graph file="FP1_0051.gxl" class="F"/>
	<graph file="FP1_0052.gxl" class="F"/>
	<graph file="FP1_0053.gxl" class="F"/>
	<graph file="FP1_0054.gxl" class="F"/>
	<graph file="FP1_0055.gxl" class="F"/>
	<graph file="FP1_0056.gxl" class="F"/>
	<graph file="FP1_0057.gxl" class="F"/>
	<graph file="FP1_0058.gxl" class="F"/>
	<graph file="FP1_0059.gxl" class="F"/>
	<graph file="FP1_0060.gxl" class="F"/>
	<graph file="FP1_0061.gxl" class="F"/>
	<graph file="FP1_0062.gxl" class="F"/>
	<graph file="FP1_0063.gxl" class="F"/>
	<graph file="FP1_0064.gxl" class="F"/>
	<graph file="FP1_0065.gxl" class="F"/>
	<graph file="FP1_0066.gxl" class="F"/>
	<graph file="FP1_0067.gxl" class="F"/>
	<graph file="FP1_0068.gxl" class="F"/>
	<graph file="FP1_0069.gxl" class="F"/>
	<graph file="FP1_0070.gxl" class="F"/>
	<graph file="FP1_0071.gxl" class="F"/>
	<graph file="FP1_0072.gxl" class="F"/>
	<graph file="FP1_0073.gxl" class="F"/>
	<graph file="FP1_0074.gxl" class="F"/>
	<graph file="FP1_0075.gxl" class="F"/>
	<graph file="FP1_0076.gxl" class="F"/>
	<graph file="FP1_0077.gxl" class="F"/>
	<graph file="FP1_0078.gxl" class="F"/>
	<graph file="FP1_0079.gxl" class="F"/>
	<graph file="FP1_0080.gxl" class="F"/>
	<graph file="FP1_0081.gxl" class="F"/>
	<graph file="FP1_0082.gxl" class="F"/>
	<graph file="FP1_0083.gxl" class="F"/>
	<graph file="FP1_0084.gxl" class="F"/>
	<graph file="FP1_0085.gxl" class="F"/>
	<graph file="FP1_0086.gxl" class="F"/>
	<graph file="FP1_0087.gxl" class="F"/>
	<graph file="FP1_0088.gxl" class="F"/>
	<graph file="FP1_0089.gxl" class="F"/>
	<graph file="FP1_0090.gxl" class="F"/>
	<graph file="FP1_0091.gxl" class="F"/>
	<graph file="FP1_0092.gxl" class="F"/>
	<graph file="FP1_0093.gxl" class="F"/>
	<graph file="FP1_0094.gxl" class="F"/>
	<graph file="FP1_0095.gxl" class="F"/>
	<graph file="FP1_0096.gxl" class="F"/>
	<graph file="FP1_0097.gxl" class="F"/>
	<graph file="FP1_0098.gxl" class="F"/>
	<graph file="FP1_0099.gxl" class="F"/>
	<graph file="FP1_0000.gxl" class="F"/>
	<graph file="FP1_0001.gxl" class="F"/>
	<graph file="FP1_0002.gxl" class="F"/>
	<graph file="FP1_0003.gxl" class="F"/>
	<graph file="FP1_0004.gxl" class="F"/>
	<graph file="FP1_0005.gxl" class="F"/>
	<graph file="FP1_0006.gxl" class="F"/>
	<graph file="FP1_0007.gxl" class="F"/>
	<graph file="FP1_0008.gxl" class="F"/>
	<graph file="FP1_0009.gxl" class="F"/>
	<graph file="FP1_0010.gxl" class="F"/>
	<graph file="FP1_0011.gxl" class="F"/>
	<graph file="FP1_0012.gxl" class="F"/>
	<graph file="FP1_0013.gxl" class="F"/>
	<graph file="FP1_0014.gxl" class="F"/>
	<graph file="FP1_0015.gxl" class="F"/>
	<graph file="FP1_0016.gxl" class="F"/>
	<graph file="FP1_0017.gxl" class="F"/>
	<graph file="FP1_0018.gxl" class="F"/>
	<graph file="FP1_0019.gxl" class="F"/>
	<graph file="FP1_0020.gxl" class="F"/>
	<graph file="FP1_0021.gxl" class="F"/>
	<graph file="FP1_0022.gxl" class="F"/>
	<graph file="FP1_0023.gxl" class="F"/>
	<graph file="FP1_0024.gxl" class="F"/>
	<graph file="FP1_0025.gxl" class="F"/>
	<graph file="FP1_0026.gxl" class="F"/>
	<graph file="FP1_0027.gxl" class="F"/>
	<graph file="FP1_0028.gxl" class="F"/>
	<graph file="FP1_0029.gxl" class="F"/>
	<graph file="FP1_0030.gxl" class="F"/>
	<graph file="FP1_0031.gxl" class="F"/>
	<graph file="FP1_0032.gxl" class="F"/>
	<graph file="FP1_0033.gxl" class="F"/>
	<graph file="FP1_0034.gxl" class="F"/>
	<graph file="FP1_0035.gxl" class="F"/>
	<graph file="FP1_0036.gxl" class="F"/>
	<graph file="FP1_0037.gxl" class="F"/>
	<graph file="FP1_0038.gxl" class="F"/>
	<graph file="FP1_0039.gxl" class="F"/>
	<graph file="FP1_0040.gxl" class="F"/>
	<graph file="FP1_0041.gxl" class="F"/>
	<graph file="FP1_0042.gxl" class="F"/>
	<graph file="FP1_0043.gxl" class="F"/>
	<graph file="FP1_0044.gxl" class="F"/>
	<graph file="FP1_0045.gxl" class="F"/>
	<graph file="FP1_0046.gxl" class="F"/>
	<graph file="FP1_0047.gxl" class="F"/>
	<graph file="FP1_0048.gxl" class="F"/>
	<graph file="FP1_0049.gxl" class="F"/>
	<graph file="FP1_0100.gxl" class="F"/>
	<graph file="FP1_0101.gxl" class="F"/>
	<graph file="FP1_0102.gxl" class="F"/>
	<graph file="FP1_0103.gxl" class="F"/>
	<graph file="FP1_0104.gxl" class="F"/>
	<graph file="FP1_0105.gxl" class="F"/>
	<graph file="FP1_0106.gxl" class="F"/>
	<graph file="FP1_0107.gxl" class="F"/>
	<graph file="FP1_0108.gxl" class="F"/>
	<graph file="FP1_0109.gxl" class="F"/>
	<graph file="FP1_0110.gxl" class="F"/>
	<graph file="FP1_0111.gxl" class="F"/>
	<graph file="FP1_0112.gxl" class="F"/>
	<graph file="FP1_0113.gxl" class="F"/>
	<graph file="FP1_0114.gxl" class="F"/>
	<graph file="FP1_0115.gxl" class="F"/>
	<graph file="FP1_0116.gxl" class="F"/>
	<graph file="FP1_0117.gxl" class="F"/>
	<graph file="FP1_0118.gxl" class="F"/>
	<graph file="FP1_0119.gxl" class="F"/>
	<graph file="FP1_0120.gxl" class="F"/>
	<graph file="FP1_0121.gxl" class="F"/>
	<graph file="FP1_0122.gxl" class="F"/>
	<graph file="FP1_0123.gxl" class="F"/>
	<graph file="FP1_0124.gxl" class="F"/>
	<graph file="FP1_0125.gxl" class="F"/>
	<graph file="FP1_0126.gxl" class="F"/>
	<graph file="FP1_0127.gxl" class="F"/>
	<graph file="FP1_0128.gxl" class="F"/>
	<graph file="FP1_0129.gxl" class="F"/>
	<graph file="FP1_0130.gxl" class="F"/>
	<graph file="FP1_0131.gxl" class="F"/>
	<graph file="FP1_0132.gxl" class="F"/>
	<graph file="FP1_0133.gxl" class="F"/>
	<graph file="FP1_0134.gxl" class="F"/>
	<graph file="FP1_0135.gxl" class="F"/>
	<graph file="FP1_0136.gxl" class="F"/>
	<graph file="FP1_0137.gxl" class="F"/>
	<graph file="FP1_0138.gxl" class="F"/>
	<graph file="FP1_0139.gxl" class="F"/>
	<graph file="FP1_0140.gxl" class="F"/>
	<graph file="FP1_0141.gxl" class="F"/>
	<graph file="FP1_0142.gxl" class="F"/>
	<graph file="FP1_0143.gxl" class="F"/>
	<graph file="FP1_0144.gxl" class="F"/>
	<graph file="FP1_0145.gxl" class="F"/>
	<graph file="FP1_0146.gxl" class="F"/>
	<graph file="FP1_0147.gxl" class="F"/>
	<graph file="FP1_0148.gxl" class="F"/>
	<graph file="FP1_0149.gxl" class="F"/>
</GraphCollection>

=== michaelflppv/mixup/gedlib/median/collections/AIDS-EDIT-NON-ISO-20-3.xml
<?xml version="1.0"?>
<!DOCTYPE GraphCollection SYSTEM "http://www.inf.unibz.it/~blumenthal/dtd/GraphCollection.dtd">
<GraphCollection>
	<graph file="molid663607_subnode_9_to_Tl.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Au.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Na.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Pb.gxl" class="1"/>
	<graph file="molid663607_addedge_1_10_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Se.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Sn.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_O.gxl" class="1"/>
	<graph file="molid663607_addnode_Mg.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Tl.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Pb.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Se.gxl" class="1"/>
	<graph file="molid663607_addedge_1_31_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_C.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Si.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Tb.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Na.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Br.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Hg.gxl" class="1"/>
	<graph file="molid663607_deledge_4_5.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Ga.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_S.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Sn.gxl" class="1"/>
	<graph file="molid663607_addedge_7_9_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_S.gxl" class="1"/>
	<graph file="molid663607_addedge_7_13_label_1.gxl" class="1"/>
	<graph file="molid663607_addnode_Na.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Zn.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Ru.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Sn.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Ge.gxl" class="1"/>
	<graph file="molid663607_addedge_3_9_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_I.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_K.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Ga.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_F.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Hg.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_Ni.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Ge.gxl" class="1"/>
	<graph file="molid663607_addnode_O.gxl" class="1"/>
	<graph file="molid663607_addnode_Sb.gxl" class="1"/>
	<graph file="molid663607_deledge_0_5.gxl" class="1"/>
	<graph file="molid663607_addnode_Br.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Ge.gxl" class="1"/>
	<graph file="molid663607_addedge_3_5_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_5_to_O.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Te.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Cu.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Si.gxl" class="1"/>
	<graph file="molid663607_addedge_0_9_label_2.gxl" class="1"/>
	<graph file="molid663607_addnode_Sn.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Cu.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Ru.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_I.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Sn.gxl" class="1"/>
	<graph file="molid663607_subedge_15_16_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Ga.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Te.gxl" class="1"/>
	<graph file="molid663607_addnode_As.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Rh.gxl" class="1"/>
	<graph file="molid663607_subnode_10_to_Tb.gxl" class="1"/>
	<graph file="molid663607_addedge_9_11_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_Ho.gxl" class="1"/>
	<graph file="molid663607_deledge_1_6.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Co.gxl" class="1"/>
	<graph file="molid663607_addedge_0_7_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Se.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_F.gxl" class="1"/>
	<graph file="molid663607_subedge_2_3_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Tl.gxl" class="1"/>
	<graph file="molid663607_addedge_0_13_label_2.gxl" class="1"/>
	<graph file="molid663607_addedge_7_14_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Mg.gxl" class="1"/>
	<graph file="molid663607_deledge_2_7.gxl" class="1"/>
	<graph file="molid663607_addedge_1_5_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_P.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Br.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_I.gxl" class="1"/>
	<graph file="molid663607_addedge_6_14_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_O.gxl" class="1"/>
	<graph file="molid663607_subnode_7_to_Rh.gxl" class="1"/>
	<graph file="molid663607_addnode_Te.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Ge.gxl" class="1"/>
	<graph file="molid663607_subnode_9_to_O.gxl" class="1"/>
	<graph file="molid663607_addedge_9_16_label_2.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Li.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Ho.gxl" class="1"/>
	<graph file="molid663607_subnode_1_to_Pb.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Ru.gxl" class="1"/>
	<graph file="molid663607_subedge_9_10_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Sb.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_Cl.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_Se.gxl" class="1"/>
	<graph file="molid663607_subnode_14_to_Rh.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_K.gxl" class="1"/>
	<graph file="molid663607_subnode_3_to_Se.gxl" class="1"/>
	<graph file="molid663607_subnode_0_to_N.gxl" class="1"/>
	<graph file="molid663607_addedge_13_15_label_1.gxl" class="1"/>
	<graph file="molid663607_subnode_13_to_F.gxl" class="1"/>
	<graph file="molid663607_subedge_1_2_to_2.gxl" class="1"/>
	<graph file="molid663607_subnode_6_to_Au.gxl" class="1"/>
</GraphCollection>
